apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-ds
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
